CREATE DATABASE todoDatabase;

CREATE TABLE todoList(
    todo_id SERIAL PRIMARY KEY,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed BOOLEAN DEFAULT FALSE
)